int ErrorFlag = 0;
static void MaxHeapify(int Heap[], int index);
void MaxHeapifyLoop(int Heap[], int index);
int BuildMaxHeap(int Heap[]);
void HeapSort(int Heap[]);
int HeapMaximum(int Heap[]);
int HeapExtractMax(int Heap[]);
void HeapInceraseKey(int Heap[], int index, int key);
void MaxHeapInsert(int Heap[], int key);
void Switch (int *x, int *y);
